#!/usr/bin/env bash
#
# This is the main script, it downloads the current "connected devices" data
# from Airwave and inserts it in database.
#
# This script is supposed to be executed periodically by a cron task.
#
# Procedure: for each access point, download the "connected devices" CSV file,
# do some conversions on the columns, and concatenate it to the previously
# downloaded files. Finally, the resulting CSV file is loaded into the DB.
#
# Note: this script assumes that the current working directory is the script's
# own enclosing directory (this is ensured by the corresponding cron task).
#
# Usage: run
#
# Daniel Weibel <danielmartin.weibel@polimi.it> Nov. 2015 - May 2016 
#------------------------------------------------------------------------------#

set -e

aux_dir=aux
out_dir=out

source "$aux_dir"/func.sh
mkdir -p "$out_dir"

cookie=$(download_cookie)
time=$(date '+%Y-%m-%d %H:%M:%S')
data="$out_dir"/last_download.csv
>"$data"

for ap_id in $(cat "$aux_dir"/ap_ids); do
  download_csv "$ap_id" "$cookie" |
  convert_csv "$ap_id" "$time" >>"$data"
done

save_csv_to_db "$data"

echo "$time,$(cat "$data" | wc -l)" >>"$out_dir"/log.csv
